import { createElement } from 'lwc';
import LwcDemo19LightningMessageService from 'c/lwcDemo19LightningMessageService';

describe('c-lwc-demo19-lightning-message-service', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-demo19-lightning-message-service', {
            is: LwcDemo19LightningMessageService
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});